//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CSVDataUtility.ClassWriter.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
[System.Serializable]
[CSVFilename("Card")]
[CSVDataAsset("CardDataTable")]
public class CardDataEntry : CSVDataUtility.IDataEntry{
            
	[CSVField("id")]
	public string id;

	[CSVField("description")]
	public string description;

	[CSVField("left text")]
	public string left_text;

	[CSVField("left value")]
	public List<int> left_value;

	[CSVField("left next card")]
	public string left_next_card;

	[CSVField("left event")]
	public CSVDataUtility.Action.ActionInfo left_event;

    [System.NonSerialized]
    public static System.Action left_event_action_none = delegate { };

    [System.NonSerialized]
    public static System.Action<string, string> left_event_action_goto_if = delegate { };

    public void Invoke_left_event()
    {
        int paramIndex = 0;

        for (int i = 0; i < left_event.callList.Count; i++)
        {
            switch (left_event.callList[i])
            {
                
                case 0:
                    left_event_action_none.Invoke();
                    paramIndex += 0;
                    break; 

                case 1:
                    left_event_action_goto_if.Invoke((string)left_event.paramList[paramIndex + 0].Value, (string)left_event.paramList[paramIndex + 1].Value);
                    paramIndex += 2;
                    break; 

            }
        }
    }

	[CSVField("right text")]
	public string right_text;

	[CSVField("right value")]
	public List<int> right_value;

	[CSVField("right next card")]
	public string right_next_card;

	[CSVField("right event")]
	public CSVDataUtility.Action.ActionInfo right_event;



    public string internal_dataEntryID { 
        get {
            return id;    
        } 
    }
    
    [CSVInternalIndex]
    public int m_internal_dataEntryIndex;
    public int internal_dataEntryIndex { get { return m_internal_dataEntryIndex; } }
}



[System.Serializable]
public class CardDataTable : CSVDataUtility.DataTable<CardDataEntry>{
    public static CardDataTable Create(){
        CardDataTable datatable = new CardDataTable();
        datatable.Read();
        return datatable;
    }
}

