//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CSVDataUtility.ClassWriter.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
[System.Serializable]
[CSVFilename("Card")]
[CSVDataAsset("CardDataTable")]
public class CardDataEntry : CSVDataUtility.IDataEntry{
            
	[CSVField("id")]
	public string id;

	[CSVField("description")]
	public string description;

	[CSVField("left text")]
	public string left_text;

	[CSVField("left value")]
	public List<int> left_value;

	[CSVField("left next card")]
	public string left_next_card;

	[CSVField("right text")]
	public string right_text;

	[CSVField("right value")]
	public List<int> right_value;

	[CSVField("right next card")]
	public string right_next_card;



    public string internal_dataEntryID { 
        get {
            return id;    
        } 
    }
    
    [CSVInternalIndex]
    public int m_internal_dataEntryIndex;
    public int internal_dataEntryIndex { get { return m_internal_dataEntryIndex; } }
}



[System.Serializable]
public class CardDataTable : CSVDataUtility.DataTable<CardDataEntry>{
    public static CardDataTable Create(){
        CardDataTable datatable = new CardDataTable();
        datatable.Read();
        return datatable;
    }
}

