//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CSVDataUtility.ClassWriter.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
[System.Serializable]
[CSVFilename("Condition")]
[CSVDataAsset("ConditionDataTable")]
public class ConditionDataEntry : CSVDataUtility.IDataEntry{
            
	[CSVField("id")]
	public string id;

	[CSVField("conditions")]
	public List<conditions_struct> conditions;

    [System.Serializable]
    public struct conditions_struct
    {
		public string variable;
		public string _operator;
		public int value;

    }



    public string internal_dataEntryID { 
        get {
            return id;    
        } 
    }
    
    [CSVInternalIndex]
    public int m_internal_dataEntryIndex;
    public int internal_dataEntryIndex { get { return m_internal_dataEntryIndex; } }
}



[System.Serializable]
public class ConditionDataTable : CSVDataUtility.DataTable<ConditionDataEntry>{
    public static ConditionDataTable Create(){
        ConditionDataTable datatable = new ConditionDataTable();
        datatable.Read();
        return datatable;
    }
}

